export { default as About } from './aboutus/About';
export { default as Chef } from './chef/Chef';
export { default as FindUs } from './findus/Findus';
export { default as Footer } from './footer/Footer';
export { default as Gallery } from './gallery/Gallery';
export { default as Header } from './header/Header';
export { default as Intro } from './intro/Intro';
export { default as Laurels } from './laurels/Laurel';
export { default as SpecialMenu } from './menu/SpecialMenu';